/* Deterministic MediaMTX YAML rendering without shell or template expansion. */

#include "gateway/mediamtx_config.h"
#include "gateway/error.h"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

typedef struct {
    char *data;
    size_t capacity;
    size_t length;
    bool failed;
} config_writer;

static void append(config_writer *writer, const char *format, ...)
{
    va_list arguments;
    size_t available;
    int written;

    if (writer->failed) {
        return;
    }
    available = writer->capacity - writer->length;
    va_start(arguments, format);
    written = vsnprintf(writer->data + writer->length, available, format,
                        arguments);
    va_end(arguments);
    if (written < 0 || (size_t)written >= available) {
        writer->failed = true;
        return;
    }
    writer->length += (size_t)written;
}

gw_status gw_mediamtx_render_config(const gw_config *config, char *output,
                                    size_t capacity, gw_error *error)
{
    config_writer writer = {output, capacity, 0U, false};
    const gw_recording_config *recording;
    size_t index;

    if (config == NULL || output == NULL || capacity == 0U) {
        gw_error_set(error, GW_ERR_ARGUMENT,
                  "configuration and output buffer are required");
        return GW_ERR_ARGUMENT;
    }
    output[0] = '\0';
    if (gw_config_validate(config, error) != GW_OK) {
        return error != NULL ? error->code : GW_ERR_VALIDATION;
    }
    recording = &config->mediamtx.recording;
    append(&writer,
           "# Generated by gatewayd; reload MediaMTX after replacing its config.\n"
           "rtsp: true\n"
           "rtspTransports: [tcp]\n"
           "rtspAddress: '127.0.0.1:8554'\n"
           "rtmp: false\n"
           "hls: false\n"
           "webrtc: true\n"
           "webrtcAddress: ':8889'\n"
           "webrtcLocalUDPAddress: ':8189'\n"
           "webrtcIPsFromInterfaces: true\n"
           "srt: false\n"
           "moq: false\n"
           "playback: %s\n"
           "playbackAddress: '%s:%u'\n"
           "pathDefaults:\n"
           "  source: publisher\n"
           "  record: false\n"
           "paths:\n",
           recording->enabled ? "true" : "false", recording->playback_listen,
           (unsigned int)recording->playback_port);
    for (index = 0U; index < config->channel_count; ++index) {
        const gw_channel_config *channel = &config->channels[index];

        append(&writer,
               "  %s:\n"
               "    record: %s\n"
               "    recordPath: '%s/%%path/%%Y-%%m-%%d_%%H-%%M-%%S-%%f'\n"
               "    recordFormat: %s\n"
               "    recordPartDuration: %ds\n"
               "    recordMaxPartSize: %dM\n"
               "    recordSegmentDuration: %ds\n"
               "    recordDeleteAfter: %ds\n",
               channel->output.path,
               recording->enabled && channel->enabled ? "true" : "false",
               recording->directory, recording->format,
               recording->part_duration_sec, recording->max_part_size_mb,
               recording->segment_duration_sec, recording->delete_after_sec);
    }
    if (writer.failed) {
        output[0] = '\0';
        gw_error_set(error, GW_ERR_OVERFLOW,
                  "MediaMTX configuration exceeds output capacity");
        return GW_ERR_OVERFLOW;
    }
    gw_error_clear(error);
    return GW_OK;
}
