d /etc/rk-media-gateway 0750 root rk-media-gateway -
d /var/lib/rk-media-gateway 0750 rk-media-gateway rk-media-gateway -
d /var/lib/rk-media-gateway/recordings 0750 rk-media-gateway rk-media-gateway -
